// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: job.proto

package job

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobService_RegisterJob_FullMethodName           = "/job.JobService/RegisterJob"
	JobService_RegisterWorker_FullMethodName        = "/job.JobService/RegisterWorker"
	JobService_UploadMediaResource_FullMethodName   = "/job.JobService/UploadMediaResource"
	JobService_DownloadMediaResource_FullMethodName = "/job.JobService/DownloadMediaResource"
	JobService_CompleteJob_FullMethodName           = "/job.JobService/CompleteJob"
	JobService_CompletePlaylist_FullMethodName      = "/job.JobService/CompletePlaylist"
	JobService_GetJob_FullMethodName                = "/job.JobService/GetJob"
	JobService_GetJobStatus_FullMethodName          = "/job.JobService/GetJobStatus"
	JobService_GetJobDetail_FullMethodName          = "/job.JobService/GetJobDetail"
	JobService_GetPlaylists_FullMethodName          = "/job.JobService/GetPlaylists"
	JobService_DownloadResource_FullMethodName      = "/job.JobService/DownloadResource"
	JobService_HeartbeatWorker_FullMethodName       = "/job.JobService/HeartbeatWorker"
)

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobServiceClient interface {
	RegisterJob(ctx context.Context, in *RegisterJobRequest, opts ...grpc.CallOption) (*RegisterJobResponse, error)
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
	UploadMediaResource(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadMediaResourceRequest, UploadMediaResourceResponse], error)
	DownloadMediaResource(ctx context.Context, in *DownloadMediaResourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadMediaResourceResponse], error)
	CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CompletePlaylist(ctx context.Context, in *CompletePlaylistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	GetJobDetail(ctx context.Context, in *GetJobDetailRequest, opts ...grpc.CallOption) (*GetJobDetailResponse, error)
	GetPlaylists(ctx context.Context, in *GetPlaylistsRequest, opts ...grpc.CallOption) (*GetPlaylistsResponse, error)
	DownloadResource(ctx context.Context, in *DownloadResourceResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HeartbeatWorker(ctx context.Context, in *HeartbeatWorkerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type jobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobServiceClient(cc grpc.ClientConnInterface) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) RegisterJob(ctx context.Context, in *RegisterJobRequest, opts ...grpc.CallOption) (*RegisterJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterJobResponse)
	err := c.cc.Invoke(ctx, JobService_RegisterJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, JobService_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) UploadMediaResource(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadMediaResourceRequest, UploadMediaResourceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobService_ServiceDesc.Streams[0], JobService_UploadMediaResource_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadMediaResourceRequest, UploadMediaResourceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobService_UploadMediaResourceClient = grpc.ClientStreamingClient[UploadMediaResourceRequest, UploadMediaResourceResponse]

func (c *jobServiceClient) DownloadMediaResource(ctx context.Context, in *DownloadMediaResourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadMediaResourceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobService_ServiceDesc.Streams[1], JobService_DownloadMediaResource_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadMediaResourceRequest, DownloadMediaResourceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobService_DownloadMediaResourceClient = grpc.ServerStreamingClient[DownloadMediaResourceResponse]

func (c *jobServiceClient) CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobService_CompleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) CompletePlaylist(ctx context.Context, in *CompletePlaylistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobService_CompletePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, JobService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, JobService_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetJobDetail(ctx context.Context, in *GetJobDetailRequest, opts ...grpc.CallOption) (*GetJobDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobDetailResponse)
	err := c.cc.Invoke(ctx, JobService_GetJobDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetPlaylists(ctx context.Context, in *GetPlaylistsRequest, opts ...grpc.CallOption) (*GetPlaylistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaylistsResponse)
	err := c.cc.Invoke(ctx, JobService_GetPlaylists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) DownloadResource(ctx context.Context, in *DownloadResourceResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobService_DownloadResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) HeartbeatWorker(ctx context.Context, in *HeartbeatWorkerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobService_HeartbeatWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServiceServer is the server API for JobService service.
// All implementations must embed UnimplementedJobServiceServer
// for forward compatibility.
type JobServiceServer interface {
	RegisterJob(context.Context, *RegisterJobRequest) (*RegisterJobResponse, error)
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	UploadMediaResource(grpc.ClientStreamingServer[UploadMediaResourceRequest, UploadMediaResourceResponse]) error
	DownloadMediaResource(*DownloadMediaResourceRequest, grpc.ServerStreamingServer[DownloadMediaResourceResponse]) error
	CompleteJob(context.Context, *CompleteJobRequest) (*emptypb.Empty, error)
	CompletePlaylist(context.Context, *CompletePlaylistRequest) (*emptypb.Empty, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	GetJobDetail(context.Context, *GetJobDetailRequest) (*GetJobDetailResponse, error)
	GetPlaylists(context.Context, *GetPlaylistsRequest) (*GetPlaylistsResponse, error)
	DownloadResource(context.Context, *DownloadResourceResponse) (*emptypb.Empty, error)
	HeartbeatWorker(context.Context, *HeartbeatWorkerRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedJobServiceServer()
}

// UnimplementedJobServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobServiceServer struct{}

func (UnimplementedJobServiceServer) RegisterJob(context.Context, *RegisterJobRequest) (*RegisterJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterJob not implemented")
}
func (UnimplementedJobServiceServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedJobServiceServer) UploadMediaResource(grpc.ClientStreamingServer[UploadMediaResourceRequest, UploadMediaResourceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadMediaResource not implemented")
}
func (UnimplementedJobServiceServer) DownloadMediaResource(*DownloadMediaResourceRequest, grpc.ServerStreamingServer[DownloadMediaResourceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadMediaResource not implemented")
}
func (UnimplementedJobServiceServer) CompleteJob(context.Context, *CompleteJobRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteJob not implemented")
}
func (UnimplementedJobServiceServer) CompletePlaylist(context.Context, *CompletePlaylistRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompletePlaylist not implemented")
}
func (UnimplementedJobServiceServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedJobServiceServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedJobServiceServer) GetJobDetail(context.Context, *GetJobDetailRequest) (*GetJobDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobDetail not implemented")
}
func (UnimplementedJobServiceServer) GetPlaylists(context.Context, *GetPlaylistsRequest) (*GetPlaylistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaylists not implemented")
}
func (UnimplementedJobServiceServer) DownloadResource(context.Context, *DownloadResourceResponse) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadResource not implemented")
}
func (UnimplementedJobServiceServer) HeartbeatWorker(context.Context, *HeartbeatWorkerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatWorker not implemented")
}
func (UnimplementedJobServiceServer) mustEmbedUnimplementedJobServiceServer() {}
func (UnimplementedJobServiceServer) testEmbeddedByValue()                    {}

// UnsafeJobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobServiceServer will
// result in compilation errors.
type UnsafeJobServiceServer interface {
	mustEmbedUnimplementedJobServiceServer()
}

func RegisterJobServiceServer(s grpc.ServiceRegistrar, srv JobServiceServer) {
	// If the following call pancis, it indicates UnimplementedJobServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobService_ServiceDesc, srv)
}

func _JobService_RegisterJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).RegisterJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_RegisterJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).RegisterJob(ctx, req.(*RegisterJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_UploadMediaResource_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JobServiceServer).UploadMediaResource(&grpc.GenericServerStream[UploadMediaResourceRequest, UploadMediaResourceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobService_UploadMediaResourceServer = grpc.ClientStreamingServer[UploadMediaResourceRequest, UploadMediaResourceResponse]

func _JobService_DownloadMediaResource_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadMediaResourceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobServiceServer).DownloadMediaResource(m, &grpc.GenericServerStream[DownloadMediaResourceRequest, DownloadMediaResourceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobService_DownloadMediaResourceServer = grpc.ServerStreamingServer[DownloadMediaResourceResponse]

func _JobService_CompleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CompleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_CompleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CompleteJob(ctx, req.(*CompleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_CompletePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletePlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CompletePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_CompletePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CompletePlaylist(ctx, req.(*CompletePlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetJobDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetJobDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_GetJobDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetJobDetail(ctx, req.(*GetJobDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetPlaylists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaylistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetPlaylists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_GetPlaylists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetPlaylists(ctx, req.(*GetPlaylistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_DownloadResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadResourceResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).DownloadResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_DownloadResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).DownloadResource(ctx, req.(*DownloadResourceResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_HeartbeatWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).HeartbeatWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_HeartbeatWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).HeartbeatWorker(ctx, req.(*HeartbeatWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobService_ServiceDesc is the grpc.ServiceDesc for JobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "job.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterJob",
			Handler:    _JobService_RegisterJob_Handler,
		},
		{
			MethodName: "RegisterWorker",
			Handler:    _JobService_RegisterWorker_Handler,
		},
		{
			MethodName: "CompleteJob",
			Handler:    _JobService_CompleteJob_Handler,
		},
		{
			MethodName: "CompletePlaylist",
			Handler:    _JobService_CompletePlaylist_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _JobService_GetJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _JobService_GetJobStatus_Handler,
		},
		{
			MethodName: "GetJobDetail",
			Handler:    _JobService_GetJobDetail_Handler,
		},
		{
			MethodName: "GetPlaylists",
			Handler:    _JobService_GetPlaylists_Handler,
		},
		{
			MethodName: "DownloadResource",
			Handler:    _JobService_DownloadResource_Handler,
		},
		{
			MethodName: "HeartbeatWorker",
			Handler:    _JobService_HeartbeatWorker_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadMediaResource",
			Handler:       _JobService_UploadMediaResource_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadMediaResource",
			Handler:       _JobService_DownloadMediaResource_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "job.proto",
}
